# Generated by Django 5.2.6 on 2025-09-13 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel', verbose_name='Personne')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
