# Generated by Django 5.2.6 on 2025-10-04 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure'),
        ),
    ]
