# Generated by Django 5.2.6 on 2025-09-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boissons', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('payer', 'Payé'), ('impayee', 'Impayée'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('type_paiement', models.CharField(choices=[('liquidite', 'Liquidité'), ('orange_money', 'Orange Money'), ('hybride', 'Hybride')], max_length=20)),
                ('montant_remis_client', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_orange', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_liquidite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monnaie_a_rendre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_monnaie', models.CharField(choices=[('remis', 'Remis'), ('avoir', 'Avoir')], default='remis', max_length=20)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('regle', 'Réglé')], default='en_attente', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avoir', to='commandes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('montant_boisson', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boissons.boisson')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.commande')),
            ],
        ),
    ]
