# Generated by Django 5.2.6 on 2025-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
