# Generated by Django 5.2.6 on 2025-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_monnaie',
            field=models.CharField(choices=[('remis', 'Remis'), ('avoir', 'Avoir'), ('non_applicable', 'Non applicable')], default='non_applicable', max_length=20),
        ),
    ]
