# Generated by Django 5.2.6 on 2025-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_montant_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='date_reglement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
