# Generated by Django 5.2.6 on 2025-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_avoir_date_reglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
