# Generated by Django 5.2.6 on 2025-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_rapportventenocturne_detailventeboisson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailVenteBoisson',
        ),
        migrations.DeleteModel(
            name='RapportVenteNocturne',
        ),
    ]
