# Generated by Django 5.2.6 on 2025-10-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_delete_detailventeboisson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='code_pays_tel',
            field=models.CharField(default='+226', max_length=5, verbose_name='Indicatif Téléphonique'),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_telephone',
            field=models.CharField(default=0, max_length=15, verbose_name='Numéro de téléphone du client'),
            preserve_default=False,
        ),
    ]
