# Generated by Django 5.2.6 on 2025-10-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_commande_client_nom_commande_client_prenom_and_more'),
        ('ventes', '0005_rapportventenocturne_caissier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='rapport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='ventes.rapportventenocturne', verbose_name='Rapport de Vente Nocturne'),
        ),
    ]
