# Generated by Django 5.2.6 on 2025-10-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_commande_rapport'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandeitem',
            old_name='montant_boisson',
            new_name='montant_produit',
        ),
        migrations.RemoveField(
            model_name='commandeitem',
            name='boisson',
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
            preserve_default=False,
        ),
    ]
