# Generated by Django 5.2.6 on 2025-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('hotesse', 'Hôtesse'), ('technicien', 'Technicien de surface'), ('caissier', 'Caissier'), ('secretaire', 'Secrétaire'), ('boss', 'Boss'), ('dj', 'DJ'), ('manager', 'Manager'), ('portier', 'Portier'), ('cuisinier', 'Cuisinier')], max_length=20)),
                ('lieu_travail', models.CharField(blank=True, choices=[('terrasse', 'Terrasse'), ('boite', 'Boîte')], max_length=10, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jours_repos', models.JSONField(blank=True, default=list)),
                ('jours_travail', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
