# Generated by Django 5.2.6 on 2025-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='change_password_required',
            field=models.BooleanField(default=True),
        ),
    ]
