# Generated by Django 5.2.6 on 2025-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personnel_change_password_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('hotesse', 'Hôtesse'), ('technicien', 'Technicien de surface'), ('caissier', 'Caissier'), ('secretaire', 'Secrétaire'), ('boss', 'Boss'), ('dj', 'DJ'), ('manager', 'Manager'), ('portier', 'Portier'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur')], max_length=20),
        ),
    ]
