# Generated by Django 5.2.6 on 2025-10-02 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boissons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportVenteNocturne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True, verbose_name='Début de la période de vente')),
                ('end_time', models.DateTimeField(verbose_name='Fin de la période de vente')),
                ('montant_total_vente', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_total_impayees', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_total_depenses', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_total_avances', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_decaisse', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('chiffre_affaire', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rapport de Vente Nocturne',
                'verbose_name_plural': 'Rapports de Vente Nocturne',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DetailVenteBoisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_totale', models.PositiveIntegerField(default=0, verbose_name='Quantité Totale Vendue')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant Total de la Boisson')),
                ('prix_unitaire_au_moment_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire de référence')),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boissons.boisson', verbose_name='Boisson')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_boissons', to='ventes.rapportventenocturne', verbose_name='Rapport de Vente')),
            ],
            options={
                'ordering': ['-montant_total'],
                'unique_together': {('rapport', 'boisson')},
            },
        ),
    ]
