# Generated by Django 5.2.6 on 2025-10-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePersonnelNocturne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_vendu_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant Total Vendu (Théorique)')),
                ('montant_impaye_personnel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant Impayé à son nom')),
                ('quantite_totale_boissons_vendues', models.PositiveIntegerField(default=0, verbose_name='Quantité Totale de Boissons Vendues')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.personnel', verbose_name='Employé concerné')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_personnel', to='ventes.rapportventenocturne', verbose_name='Rapport de Vente Nocturne')),
            ],
            options={
                'verbose_name': 'Performance du Personnel Nocturne',
                'unique_together': {('rapport', 'personnel')},
            },
        ),
    ]
