# Generated by Django 5.2.6 on 2025-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_performancepersonnelnocturne'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancepersonnelnocturne',
            name='montant_total_avances_personnel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant Total des Avances'),
        ),
    ]
