# Generated by Django 5.2.6 on 2025-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_performancepersonnelnocturne_montant_total_avances_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancepersonnelnocturne',
            name='details_boissons_vendues_archive',
            field=models.JSONField(blank=True, null=True, verbose_name='Détail des boissons vendues archivé'),
        ),
    ]
