# Generated by Django 5.2.6 on 2025-10-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        ('ventes', '0004_performancepersonnelnocturne_details_boissons_vendues_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportventenocturne',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.personnel', verbose_name='Caissier Responsable de la Session'),
        ),
        migrations.AddField(
            model_name='rapportventenocturne',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Session de Vente Active'),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de la période de vente'),
        ),
        migrations.AddConstraint(
            model_name='rapportventenocturne',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_session'),
        ),
    ]
