# Generated by Django 5.2.6 on 2025-10-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_approvisionnement_quantite_recue_total'),
        ('ventes', '0005_rapportventenocturne_caissier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancepersonnelnocturne',
            options={'verbose_name': 'Performance du Personnel Nocturne', 'verbose_name_plural': 'Performances du Personnel Nocturne'},
        ),
        migrations.RemoveField(
            model_name='performancepersonnelnocturne',
            name='details_boissons_vendues_archive',
        ),
        migrations.RemoveField(
            model_name='performancepersonnelnocturne',
            name='quantite_totale_boissons_vendues',
        ),
        migrations.RemoveField(
            model_name='rapportventenocturne',
            name='montant_total_vente',
        ),
        migrations.AddField(
            model_name='performancepersonnelnocturne',
            name='details_produits_vendus_archive',
            field=models.JSONField(blank=True, null=True, verbose_name='Détail des produits vendus archivé'),
        ),
        migrations.AddField(
            model_name='performancepersonnelnocturne',
            name='quantite_totale_produits_vendus',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité Totale de Produits Vendus'),
        ),
        migrations.AddField(
            model_name='rapportventenocturne',
            name='benefice_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Bénéfice Net (Marge - Dépenses)'),
        ),
        migrations.AddField(
            model_name='rapportventenocturne',
            name='marge_totale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Marge Totale Réalisée'),
        ),
        migrations.AlterField(
            model_name='performancepersonnelnocturne',
            name='montant_vendu_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Chiffre d'Affaire Réalisé"),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='chiffre_affaire',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Chiffre d'Affaire Total"),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='montant_decaisse',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total Décaissé (Dépenses + Avances)'),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='montant_total_avances',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total des Avances'),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='montant_total_depenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total des Dépenses'),
        ),
        migrations.AlterField(
            model_name='rapportventenocturne',
            name='montant_total_impayees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total des Impayés'),
        ),
        migrations.CreateModel(
            name='DetailVenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_totale', models.PositiveIntegerField(default=0, verbose_name='Quantité Totale Vendue')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant Total des Ventes')),
                ('marge_totale_produit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marge Totale du Produit')),
                ('prix_unitaire_au_moment_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire de vente')),
                ('marge_unitaire_au_moment_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Marge unitaire de référence')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit', verbose_name='Produit')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_produits', to='ventes.rapportventenocturne', verbose_name='Rapport de Vente')),
            ],
            options={
                'verbose_name': 'Détail de Vente Produit',
                'verbose_name_plural': 'Détails de Vente Produit',
                'ordering': ['-montant_total'],
                'unique_together': {('rapport', 'produit')},
            },
        ),
    ]
