# Generated by Django 5.2.6 on 2025-09-13 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant de l'avance")),
                ('date_avance', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'avance")),
                ('motif', models.CharField(blank=True, max_length=255, null=True, verbose_name="Motif de l'avance")),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='personnel.personnel')),
            ],
        ),
    ]
