# Generated by Django 5.2.6 on 2025-10-04 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='date_avance',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de l'avance"),
        ),
    ]
