# Generated by Django 5.2.6 on 2025-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boissons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boisson',
            options={'ordering': ['lieu', 'nom'], 'verbose_name': 'Boisson', 'verbose_name_plural': 'Boissons'},
        ),
        migrations.AddField(
            model_name='boisson',
            name='lieu',
            field=models.CharField(choices=[('boite', 'Boîte'), ('terrasse', 'Terrasse')], default='boite', max_length=20, verbose_name='Lieu de vente'),
        ),
    ]
