# Generated by Django 5.2.6 on 2025-09-12 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stock_initial', models.PositiveIntegerField()),
                ('stock_actuel', models.PositiveIntegerField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='stocks.boisson')),
            ],
        ),
    ]
