# Generated by Django 5.2.6 on 2025-10-25 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de Produit',
                'verbose_name_plural': 'Catégories de Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de la session d'inventaire")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé et appliqué'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de la validation')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('produits_perdus_total', models.PositiveIntegerField(default=0, verbose_name='Total Qté Perdue')),
                ('produits_retrouves_total', models.PositiveIntegerField(default=0, verbose_name='Total Qté Retrouvée')),
                ('prix_achat_perte_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total PA Perdu')),
                ('prix_vente_perte_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total PV Perdu')),
                ('prix_achat_retrouves_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total PA Retrouvé')),
                ('prix_vente_retrouves_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total PV Retrouvé')),
                ('marge_perdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Marge Perdue')),
                ('marge_retrouvee_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Marge Retrouvée')),
                ('gain_net_global', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gain Net Global')),
                ('initiateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_initiés', to=settings.AUTH_USER_MODEL, verbose_name="Personnel initiateur de l'inventaire")),
                ('secretaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_validés', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire/Manager Validateur')),
            ],
            options={
                'verbose_name': "Session d'Inventaire",
                'verbose_name_plural': "Sessions d'Inventaire",
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('denombrable', 'Dénombrable (Stock)'), ('non_denombrable', 'Non Dénombrable (Vente par plat/unité)')], default='denombrable', max_length=20, verbose_name='Nature de stock')),
                ('lieu', models.CharField(choices=[('boite', 'Boîte'), ('terrasse', 'Terrasse')], default='boite', max_length=20, verbose_name='Lieu de vente')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Produit actif (en vente)')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat (FCFA)")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)')),
                ('marge', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Marge (Bénéfice)')),
                ('stock_initial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('stock_actuel', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.categorieproduit', verbose_name='Catégorie de produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-is_active', 'categorie__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('stock_actuel', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('stock_compte', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock Physique Compté')),
                ('quantite_perte', models.PositiveIntegerField(default=0, verbose_name='Quantité Perdue/Endommagée (Calculé ou Saisi)')),
                ('quantite_retrouvee', models.PositiveIntegerField(default=0, verbose_name='Quantité Retrouvée/Ajoutée (Calculé ou Saisi)')),
                ('justification', models.TextField(blank=True, null=True)),
                ('prix_achat_perte', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='PA Perte')),
                ('prix_vente_perte', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='PV Perte')),
                ('marge_perdue', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Marge Perdue')),
                ('prix_achat_retrouves', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='PA Retrouvé')),
                ('prix_vente_retrouves', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='PV Retrouvé')),
                ('marge_retrouvee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Marge Retrouvée')),
                ('gain_net_ligne', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Gain Net de la Ligne')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.inventaire', verbose_name="Session d'Inventaire parente")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='produits.produit', verbose_name='Produit concerné')),
            ],
            options={
                'verbose_name': "Ligne d'Inventaire",
                'verbose_name_plural': "Lignes d'Inventaire",
                'ordering': ('produit__nom',),
            },
        ),
    ]
