# Generated by Django 5.2.6 on 2025-10-27 12:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du Fournisseur')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom/Référence de l'Approvisionnement")),
                ('date_approvisionnement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Réception')),
                ('telephone_fournisseur', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Téléphone (snapshot)')),
                ('cout_transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Coût du Transport')),
                ('montant_achats_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Montant Total des Achats (Produits)')),
                ('cout_approvisionnement_global', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name="Coût Global de l'Approvisionnement")),
                ('quantite_perdue_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité Totale Perdue')),
                ('montant_perte_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Montant Total des Pertes')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de Validation/Contrôle')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé et appliqué'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name="Statut de l'Approvisionnement")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('controleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements_controles', to=settings.AUTH_USER_MODEL, verbose_name='Contrôleur/Validateur')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Personnel ayant enregistré')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements', to='produits.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ('-date_approvisionnement',),
            },
        ),
        migrations.CreateModel(
            name='LigneApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(choices=[('boite', 'Boîte'), ('terrasse', 'Terrasse')], default='boite', max_length=20, verbose_name='Lieu de Stockage')),
                ('quantite_recue', models.PositiveIntegerField(default=0, verbose_name='Quantité Approvisionnée (Reçue)')),
                ('quantite_endommagee', models.PositiveIntegerField(default=0, verbose_name='Quantité Endommagée/Perdue à la Réception')),
                ('quantite_nette', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité Nette (pour le stock)')),
                ('montant_total_produit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Coût Total Facturé pour ce Produit')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name="Prix d'Achat Unitaire (Calculé)")),
                ('montant_perte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Montant Perte (Endommagement)')),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_appro', to='produits.approvisionnement', verbose_name='Approvisionnement parent')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_appro', to='produits.produit', verbose_name='Produit concerné')),
            ],
            options={
                'verbose_name': "Ligne d'Approvisionnement",
                'verbose_name_plural': "Lignes d'Approvisionnement",
                'ordering': ('produit__nom',),
            },
        ),
    ]
