# Generated by Django 5.2.6 on 2025-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_fournisseur_approvisionnement_ligneapprovisionnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(default=67489187, max_length=20, unique=True, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
