# Generated by Django 5.2.6 on 2025-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_fournisseur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='quantite_recue_total',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité Totale Reçue'),
        ),
    ]
